In [54]:
import pandas as pd
import statsmodels.formula.api as sm
from statsmodels.sandbox.regression.predstd import wls_prediction_std
from sklearn import preprocessing
from sklearn.preprocessing import scale, robust_scale, minmax_scale, maxabs_scale

In [55]:
pizza1 = pd.read_excel('data_pizza/data_1.xls',header=None)
pizza2 = pd.read_excel('data_pizza/data_2.xls',header=None)
pizza3 = pd.read_excel('data_pizza/data_3.xls',header=None)
pizza4 = pd.read_excel('data_pizza/data_4.xls',header=None)
pizza5 = pd.read_excel('data_pizza/data_5.xls',header=None)
pizza6 = pd.read_excel('data_pizza/data_6.xls',header=None)
pizza7 = pd.read_excel('data_pizza/data_7.xls',header=None)
pizza8 = pd.read_excel('data_pizza/data_8.xls',header=None)
pizza9 = pd.read_excel('data_pizza/data_9.xls',header=None)
pizza10 = pd.read_excel('data_pizza/data_10.xls',header=None)
pizza11 = pd.read_excel('data_pizza/data_11.xls',header=None)
pizza12 = pd.read_excel('data_pizza/data_12.xls',header=None)

In [56]:
frames = [pizza1, pizza2, pizza3, pizza4, pizza5, pizza6, pizza7, pizza8, pizza9, pizza10, pizza11, pizza12]

In [57]:
result = pd.concat(frames)

In [58]:
result

      0       1     2  3  4  5  6
0   106  208904  1032  1  0  0  0
1    67  160021   395  1  0  0  0
2    52  125580   192  1  0  0  0
3    64  222652   381  1  0  0  0
4    72  230570   275  1  0  0  0
5    56  146196   140  1  0  0  0
6    61  156671   245  1  0  0  0
7    40   93402   100  1  0  0  0
8    85  204606   403  1  0  0  0
9    37  125384    85  1  0  0  0
10   46  145179   195  1  0  0  0
11   61  159770   165  1  0  0  0
12   51  153610   190  1  0  0  0
13   49  126581   321  1  0  0  0
14   68  155051   331  1  0  0  0
15   41  116401   118  1  0  0  0
16   70  174370   150  1  0  0  0
17   79  230801   300  1  0  0  0
18   58  163253   125  1  0  0  0
19   63  146904   305  1  0  0  0
20   53   90164   295  1  0  0  0
21   53  178775   276  1  0  0  0
22   46   60786   120  1  0  0  0
23   50   51503   360  1  0  0  0
24   43  157571   130  1  0  0  0
25  106  208904  5855  0  1  0  0
26   67  160021  4377  0  1  0  0
27   52  125580  2843  0  1  0  0
28   64  222652  5828  0  1  0  0
29   72  230570  3486  0  1  0  0
..  ...     ...   ... .. .. .. ..
70   53   90164  6748  0  0  1  0
71   53  178775  7090  0  0  1  0
72   46   60786  4081  0  0  1  0
73   50   51503  5987  0  0  1  0
74   43  157571  5520  0  0  1  0
75  106  208904  3111  0  0  0  1
76   67  160021  1339  0  0  0  1
77   52  125580  1259  0  0  0  1
78   64  222652  2067  0  0  0  1
79   72  230570  1785  0  0  0  1
80   56  146196   489  0  0  0  1
81   61  156671  1007  0  0  0  1
82   40   93402   714  0  0  0  1
83   85  204606  1141  0  0  0  1
84   37  125384   760  0  0  0  1
85   46  145179   715  0  0  0  1
86   61  159770   854  0  0  0  1
87   51  153610   876  0  0  0  1
88   49  126581  1130  0  0  0  1
89   68  155051   837  0  0  0  1
90   41  116401   591  0  0  0  1
91   70  174370   958  0  0  0  1
92   79  230801  1066  0  0  0  1
93   58  163253   537  0  0  0  1
94   63  146904  1372  0  0  0  1
95   53   90164  1208  0  0  0  1
96   53  178775  1066  0  0  0  1
97   46   60786   355  0  0  0  1
98   50   51503   701  0  0  0  1
99   43  157571  1263  0  0  0  1

[1200 rows x 7 columns]

In [59]:
# 각 column에 indexing
result.columns = ["total_number", "house", "call", "morning", "lunch", "dinner","yasik"]
print(result.head())
print(result)

   total_number   house  call  morning  lunch  dinner  yasik
0           106  208904  1032        1      0       0      0
1            67  160021   395        1      0       0      0
2            52  125580   192        1      0       0      0
3            64  222652   381        1      0       0      0
4            72  230570   275        1      0       0      0
    total_number   house  call  morning  lunch  dinner  yasik
0            106  208904  1032        1      0       0      0
1             67  160021   395        1      0       0      0
2             52  125580   192        1      0       0      0
3             64  222652   381        1      0       0      0
4             72  230570   275        1      0       0      0
5             56  146196   140        1      0       0      0
6             61  156671   245        1      0       0      0
7             40   93402   100        1      0       0      0
8             85  204606   403        1      0       0      0
9             37  125384    85        1      0       0      0
10            46  145179   195        1      0       0      0
11            61  159770   165        1      0       0      0
12            51  153610   190        1      0       0      0
13            49  126581   321        1      0       0      0
14            68  155051   331        1      0       0      0
15            41  116401   118        1      0       0      0
16            70  174370   150        1      0       0      0
17            79  230801   300        1      0       0      0
18            58  163253   125        1      0       0      0
19            63  146904   305        1      0       0      0
20            53   90164   295        1      0       0      0
21            53  178775   276        1      0       0      0
22            46   60786   120        1      0       0      0
23            50   51503   360        1      0       0      0
24            43  157571   130        1      0       0      0
25           106  208904  5855        0      1       0      0
26            67  160021  4377        0      1       0      0
27            52  125580  2843        0      1       0      0
28            64  222652  5828        0      1       0      0
29            72  230570  3486        0      1       0      0
..           ...     ...   ...      ...    ...     ...    ...
70            53   90164  6748        0      0       1      0
71            53  178775  7090        0      0       1      0
72            46   60786  4081        0      0       1      0
73            50   51503  5987        0      0       1      0
74            43  157571  5520        0      0       1      0
75           106  208904  3111        0      0       0      1
76            67  160021  1339        0      0       0      1
77            52  125580  1259        0      0       0      1
78            64  222652  2067        0      0       0      1
79            72  230570  1785        0      0       0      1
80            56  146196   489        0      0       0      1
81            61  156671  1007        0      0       0      1
82            40   93402   714        0      0       0      1
83            85  204606  1141        0      0       0      1
84            37  125384   760        0      0       0      1
85            46  145179   715        0      0       0      1
86            61  159770   854        0      0       0      1
87            51  153610   876        0      0       0      1
88            49  126581  1130        0      0       0      1
89            68  155051   837        0      0       0      1
90            41  116401   591        0      0       0      1
91            70  174370   958        0      0       0      1
92            79  230801  1066        0      0       0      1
93            58  163253   537        0      0       0      1
94            63  146904  1372        0      0       0      1
95            53   90164  1208        0      0       0      1
96            53  178775  1066        0      0       0      1
97            46   60786   355        0      0       0      1
98            50   51503   701        0      0       0      1
99            43  157571  1263        0      0       0      1

[1200 rows x 7 columns]

In [60]:
# 한달에 한 가게가 받는 콜 수 column 추가
result['call_for_onestore'] = result['call']/result['total_number']

In [61]:
# Normalization으로 Min-Max scaler 사용
min_max_scaler = preprocessing.MinMaxScaler()
x = result['total_number'].values.astype(float)
x = x.reshape(-1,1)
x_scaled = min_max_scaler.fit_transform(x)
result['total_number'] = pd.DataFrame(x_scaled)

In [62]:
x = result['house'].values.astype(float)
x = x.reshape(-1,1)
x_scaled = min_max_scaler.fit_transform(x)
result['house'] = pd.DataFrame(x_scaled)

In [63]:
# Multivariable regression
LP_result = sm.ols(formula = 'call_for_onestore ~ total_number + house + morning + lunch + dinner + yasik', data = result).fit()

In [64]:
print(LP_result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:      call_for_onestore   R-squared:                       0.812
Model:                            OLS   Adj. R-squared:                  0.811
Method:                 Least Squares   F-statistic:                     1032.
Date:                Wed, 06 Dec 2017   Prob (F-statistic):               0.00
Time:                        23:51:02   Log-Likelihood:                -5090.5
No. Observations:                1200   AIC:                         1.019e+04
Df Residuals:                    1194   BIC:                         1.022e+04
Df Model:                           5
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       27.8792      0.924     30.160      0.000      26.066      29.693
total_number   -13.7979      3.039     -4.541      0.000     -19.759      -7.836
house           15.6422      2.611      5.990      0.000      10.519      20.766
morning        -28.9158      0.875    -33.059      0.000     -30.632     -27.200
lunch           12.9652      0.875     14.823      0.000      11.249      14.681
dinner          61.2184      0.875     69.991      0.000      59.502      62.934
yasik          -17.3885      0.875    -19.880      0.000     -19.105     -15.672
==============================================================================
Omnibus:                      193.730   Durbin-Watson:                   1.543
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1833.975
Skew:                           0.429   Prob(JB):                         0.00
Kurtosis:                       8.995   Cond. No.                     6.10e+15
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.44e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.