In [57]:
import pandas as pd
import statsmodels.formula.api as sm
from statsmodels.sandbox.regression.predstd import wls_prediction_std
from sklearn import preprocessing
from sklearn.preprocessing import scale, robust_scale, minmax_scale, maxabs_scale
from pandas import ExcelWriter
from pandas import ExcelFile

In [58]:
chinese1 = pd.read_excel('data_chinese/data_1.xls',header=None)
chinese2 = pd.read_excel('data_chinese/data_2.xls',header=None)
chinese3 = pd.read_excel('data_chinese/data_3.xls',header=None)
chinese4 = pd.read_excel('data_chinese/data_4.xls',header=None)
chinese5 = pd.read_excel('data_chinese/data_5.xls',header=None)
chinese6 = pd.read_excel('data_chinese/data_6.xls',header=None)
chinese7 = pd.read_excel('data_chinese/data_7.xls',header=None)
chinese8 = pd.read_excel('data_chinese/data_8.xls',header=None)
chinese9 = pd.read_excel('data_chinese/data_9.xls',header=None)
chinese10 = pd.read_excel('data_chinese/data_10.xls',header=None)
chinese11 = pd.read_excel('data_chinese/data_11.xls',header=None)
chinese12 = pd.read_excel('data_chinese/data_12.xls',header=None)

In [59]:
frames = [chinese1,chinese2,chinese3,chinese4,chinese5,chinese6,chinese7,chinese8,chinese9,chinese10,chinese11,chinese12]

In [60]:
result = pd.concat(frames)

In [61]:
result

      0       1      2  3  4  5  6
0   206  208904   4414  1  0  0  0
1    76  160021   1454  1  0  0  0
2    51  125580   1242  1  0  0  0
3    85  222652   2759  1  0  0  0
4    89  230570   1874  1  0  0  0
5   124  146196    811  1  0  0  0
6   217  156671   1131  1  0  0  0
7    82   93402    792  1  0  0  0
8    73  204606   1023  1  0  0  0
9    51  125384    690  1  0  0  0
10   88  145179   2039  1  0  0  0
11   48  159770    867  1  0  0  0
12  124  153610   1695  1  0  0  0
13   55  126581   1731  1  0  0  0
14  136  155051   2003  1  0  0  0
15   68  116401    969  1  0  0  0
16   77  174370   1275  1  0  0  0
17  114  230801   2020  1  0  0  0
18   60  163253    681  1  0  0  0
19  222  146904   1767  1  0  0  0
20   72   90164   2108  1  0  0  0
21   74  178775   1149  1  0  0  0
22   98   60786   1798  1  0  0  0
23   98   51503   2885  1  0  0  0
24   74  157571   1353  1  0  0  0
25  206  208904  26623  0  1  0  0
26   76  160021  13835  0  1  0  0
27   51  125580   9721  0  1  0  0
28   85  222652  17994  0  1  0  0
29   89  230570  13355  0  1  0  0
..  ...     ...    ... .. .. .. ..
70   72   90164  13504  0  0  1  0
71   74  178775   9059  0  0  1  0
72   98   60786   9652  0  0  1  0
73   98   51503  15490  0  0  1  0
74   74  157571   7181  0  0  1  0
75  206  208904   4427  0  0  0  1
76   76  160021    880  0  0  0  1
77   51  125580   1866  0  0  0  1
78   85  222652   4464  0  0  0  1
79   89  230570   2325  0  0  0  1
80  124  146196   1165  0  0  0  1
81  217  156671    610  0  0  0  1
82   82   93402    700  0  0  0  1
83   73  204606    530  0  0  0  1
84   51  125384    390  0  0  0  1
85   88  145179   3057  0  0  0  1
86   48  159770    525  0  0  0  1
87  124  153610   1986  0  0  0  1
88   55  126581   1801  0  0  0  1
89  136  155051    660  0  0  0  1
90   68  116401   1561  0  0  0  1
91   77  174370    640  0  0  0  1
92  114  230801   3050  0  0  0  1
93   60  163253    799  0  0  0  1
94  222  146904    870  0  0  0  1
95   72   90164    822  0  0  0  1
96   74  178775   2099  0  0  0  1
97   98   60786   1426  0  0  0  1
98   98   51503   2757  0  0  0  1
99   74  157571   2377  0  0  0  1

[1200 rows x 7 columns]

In [62]:
# 각 column에 indexing
result.columns = ["total_number", "house", "call", "morning", "lunch", "dinner","yasik"]
print(result.head())
print(result)

   total_number   house  call  morning  lunch  dinner  yasik
0           206  208904  4414        1      0       0      0
1            76  160021  1454        1      0       0      0
2            51  125580  1242        1      0       0      0
3            85  222652  2759        1      0       0      0
4            89  230570  1874        1      0       0      0
    total_number   house   call  morning  lunch  dinner  yasik
0            206  208904   4414        1      0       0      0
1             76  160021   1454        1      0       0      0
2             51  125580   1242        1      0       0      0
3             85  222652   2759        1      0       0      0
4             89  230570   1874        1      0       0      0
5            124  146196    811        1      0       0      0
6            217  156671   1131        1      0       0      0
7             82   93402    792        1      0       0      0
8             73  204606   1023        1      0       0      0
9             51  125384    690        1      0       0      0
10            88  145179   2039        1      0       0      0
11            48  159770    867        1      0       0      0
12           124  153610   1695        1      0       0      0
13            55  126581   1731        1      0       0      0
14           136  155051   2003        1      0       0      0
15            68  116401    969        1      0       0      0
16            77  174370   1275        1      0       0      0
17           114  230801   2020        1      0       0      0
18            60  163253    681        1      0       0      0
19           222  146904   1767        1      0       0      0
20            72   90164   2108        1      0       0      0
21            74  178775   1149        1      0       0      0
22            98   60786   1798        1      0       0      0
23            98   51503   2885        1      0       0      0
24            74  157571   1353        1      0       0      0
25           206  208904  26623        0      1       0      0
26            76  160021  13835        0      1       0      0
27            51  125580   9721        0      1       0      0
28            85  222652  17994        0      1       0      0
29            89  230570  13355        0      1       0      0
..           ...     ...    ...      ...    ...     ...    ...
70            72   90164  13504        0      0       1      0
71            74  178775   9059        0      0       1      0
72            98   60786   9652        0      0       1      0
73            98   51503  15490        0      0       1      0
74            74  157571   7181        0      0       1      0
75           206  208904   4427        0      0       0      1
76            76  160021    880        0      0       0      1
77            51  125580   1866        0      0       0      1
78            85  222652   4464        0      0       0      1
79            89  230570   2325        0      0       0      1
80           124  146196   1165        0      0       0      1
81           217  156671    610        0      0       0      1
82            82   93402    700        0      0       0      1
83            73  204606    530        0      0       0      1
84            51  125384    390        0      0       0      1
85            88  145179   3057        0      0       0      1
86            48  159770    525        0      0       0      1
87           124  153610   1986        0      0       0      1
88            55  126581   1801        0      0       0      1
89           136  155051    660        0      0       0      1
90            68  116401   1561        0      0       0      1
91            77  174370    640        0      0       0      1
92           114  230801   3050        0      0       0      1
93            60  163253    799        0      0       0      1
94           222  146904    870        0      0       0      1
95            72   90164    822        0      0       0      1
96            74  178775   2099        0      0       0      1
97            98   60786   1426        0      0       0      1
98            98   51503   2757        0      0       0      1
99            74  157571   2377        0      0       0      1

[1200 rows x 7 columns]

In [63]:
# 한달에 한 가게가 받는 콜 수 column 추가
result['call_for_onestore'] = result['call']/result['total_number']

In [64]:
# Normalization으로 Min-Max scaler 사용
min_max_scaler = preprocessing.MinMaxScaler()
x = result['total_number'].values.astype(float)
x = x.reshape(-1,1)
x_scaled = min_max_scaler.fit_transform(x)
result['total_number'] = pd.DataFrame(x_scaled)

In [65]:
x = result['house'].values.astype(float)
x = x.reshape(-1,1)
x_scaled = min_max_scaler.fit_transform(x)
result['house'] = pd.DataFrame(x_scaled)

In [66]:
# Multivariable regression
LP_result = sm.ols(formula = 'call_for_onestore ~ total_number + house + morning + lunch + dinner + yasik', data = result).fit()

In [67]:
print(LP_result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:      call_for_onestore   R-squared:                       0.663
Model:                            OLS   Adj. R-squared:                  0.661
Method:                 Least Squares   F-statistic:                     469.0
Date:                Wed, 06 Dec 2017   Prob (F-statistic):          1.15e-278
Time:                        23:49:43   Log-Likelihood:                -5949.4
No. Observations:                1200   AIC:                         1.191e+04
Df Residuals:                    1194   BIC:                         1.194e+04
Df Model:                           5
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       54.0674      1.967     27.484      0.000      50.208      57.927
total_number   -48.2863      3.609    -13.380      0.000     -55.367     -41.206
house           14.6576      3.898      3.760      0.000       7.010      22.305
morning        -32.5128      1.794    -18.119      0.000     -36.033     -28.992
lunch           66.3347      1.794     36.967      0.000      62.814      69.855
dinner          52.9002      1.794     29.480      0.000      49.380      56.421
yasik          -32.6547      1.794    -18.198      0.000     -36.175     -29.134
==============================================================================
Omnibus:                      114.384   Durbin-Watson:                   1.754
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              221.426
Skew:                           0.613   Prob(JB):                     8.28e-49
Kurtosis:                       4.711   Cond. No.                     6.22e+15
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.17e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.