In [55]:
import pandas as pd
import statsmodels.formula.api as sm
from statsmodels.sandbox.regression.predstd import wls_prediction_std
from sklearn import preprocessing
from sklearn.preprocessing import scale, robust_scale, minmax_scale, maxabs_scale

In [56]:
pigfoot1 = pd.read_excel('data_pigfoot/data_1.xls',header=None)
pigfoot2 = pd.read_excel('data_pigfoot/data_2.xls',header=None)
pigfoot3 = pd.read_excel('data_pigfoot/data_3.xls',header=None)
pigfoot4 = pd.read_excel('data_pigfoot/data_4.xls',header=None)
pigfoot5 = pd.read_excel('data_pigfoot/data_5.xls',header=None)
pigfoot6 = pd.read_excel('data_pigfoot/data_6.xls',header=None)
pigfoot7 = pd.read_excel('data_pigfoot/data_7.xls',header=None)
pigfoot8 = pd.read_excel('data_pigfoot/data_8.xls',header=None)
pigfoot9 = pd.read_excel('data_pigfoot/data_9.xls',header=None)
pigfoot10 = pd.read_excel('data_pigfoot/data_10.xls',header=None)
pigfoot11 = pd.read_excel('data_pigfoot/data_11.xls',header=None)
pigfoot12 = pd.read_excel('data_pigfoot/data_12.xls',header=None)

In [57]:
frames = [pigfoot1,pigfoot2,pigfoot3,pigfoot4,pigfoot5,pigfoot6,pigfoot7,pigfoot8,pigfoot9,pigfoot10,pigfoot11,pigfoot12]

In [58]:
result = pd.concat(frames)

In [59]:
result

     0       1     2  3  4  5  6
0   83  208904   475  1  0  0  0
1   71  160021   140  1  0  0  0
2   75  125580   105  1  0  0  0
3   77  222652   395  1  0  0  0
4   76  230570   186  1  0  0  0
5   68  146196    70  1  0  0  0
6   69  156671    75  1  0  0  0
7   45   93402   125  1  0  0  0
8   54  204606   150  1  0  0  0
9   49  125384    45  1  0  0  0
10  51  145179   400  1  0  0  0
11  48  159770    55  1  0  0  0
12  67  153610   145  1  0  0  0
13  33  126581   170  1  0  0  0
14  49  155051   375  1  0  0  0
15  60  116401   192  1  0  0  0
16  75  174370   110  1  0  0  0
17  97  230801   638  1  0  0  0
18  60  163253    70  1  0  0  0
19  56  146904   280  1  0  0  0
20  39   90164   250  1  0  0  0
21  64  178775    55  1  0  0  0
22  33   60786   160  1  0  0  0
23  52   51503   410  1  0  0  0
24  63  157571    65  1  0  0  0
25  83  208904  2562  0  1  0  0
26  71  160021  1296  0  1  0  0
27  75  125580   896  0  1  0  0
28  77  222652  1962  0  1  0  0
29  76  230570  1332  0  1  0  0
..  ..     ...   ... .. .. .. ..
70  39   90164  2886  0  0  1  0
71  64  178775  2311  0  0  1  0
72  33   60786  2610  0  0  1  0
73  52   51503  2703  0  0  1  0
74  63  157571  3698  0  0  1  0
75  83  208904  2333  0  0  0  1
76  71  160021  1237  0  0  0  1
77  75  125580   790  0  0  0  1
78  77  222652  1164  0  0  0  1
79  76  230570   725  0  0  0  1
80  68  146196   733  0  0  0  1
81  69  156671   618  0  0  0  1
82  45   93402   485  0  0  0  1
83  54  204606   833  0  0  0  1
84  49  125384   445  0  0  0  1
85  51  145179  1071  0  0  0  1
86  48  159770   670  0  0  0  1
87  67  153610   395  0  0  0  1
88  33  126581   671  0  0  0  1
89  49  155051  1056  0  0  0  1
90  60  116401   843  0  0  0  1
91  75  174370  1023  0  0  0  1
92  97  230801  1071  0  0  0  1
93  60  163253   295  0  0  0  1
94  56  146904  1195  0  0  0  1
95  39   90164   425  0  0  0  1
96  64  178775   547  0  0  0  1
97  33   60786   505  0  0  0  1
98  52   51503  1362  0  0  0  1
99  63  157571   948  0  0  0  1

[1200 rows x 7 columns]

In [60]:
# 각 column에 indexing
result.columns = ["total_number", "house", "call", "morning", "lunch", "dinner","yasik"]
print(result.head())
print(result)

   total_number   house  call  morning  lunch  dinner  yasik
0            83  208904   475        1      0       0      0
1            71  160021   140        1      0       0      0
2            75  125580   105        1      0       0      0
3            77  222652   395        1      0       0      0
4            76  230570   186        1      0       0      0
    total_number   house  call  morning  lunch  dinner  yasik
0             83  208904   475        1      0       0      0
1             71  160021   140        1      0       0      0
2             75  125580   105        1      0       0      0
3             77  222652   395        1      0       0      0
4             76  230570   186        1      0       0      0
5             68  146196    70        1      0       0      0
6             69  156671    75        1      0       0      0
7             45   93402   125        1      0       0      0
8             54  204606   150        1      0       0      0
9             49  125384    45        1      0       0      0
10            51  145179   400        1      0       0      0
11            48  159770    55        1      0       0      0
12            67  153610   145        1      0       0      0
13            33  126581   170        1      0       0      0
14            49  155051   375        1      0       0      0
15            60  116401   192        1      0       0      0
16            75  174370   110        1      0       0      0
17            97  230801   638        1      0       0      0
18            60  163253    70        1      0       0      0
19            56  146904   280        1      0       0      0
20            39   90164   250        1      0       0      0
21            64  178775    55        1      0       0      0
22            33   60786   160        1      0       0      0
23            52   51503   410        1      0       0      0
24            63  157571    65        1      0       0      0
25            83  208904  2562        0      1       0      0
26            71  160021  1296        0      1       0      0
27            75  125580   896        0      1       0      0
28            77  222652  1962        0      1       0      0
29            76  230570  1332        0      1       0      0
..           ...     ...   ...      ...    ...     ...    ...
70            39   90164  2886        0      0       1      0
71            64  178775  2311        0      0       1      0
72            33   60786  2610        0      0       1      0
73            52   51503  2703        0      0       1      0
74            63  157571  3698        0      0       1      0
75            83  208904  2333        0      0       0      1
76            71  160021  1237        0      0       0      1
77            75  125580   790        0      0       0      1
78            77  222652  1164        0      0       0      1
79            76  230570   725        0      0       0      1
80            68  146196   733        0      0       0      1
81            69  156671   618        0      0       0      1
82            45   93402   485        0      0       0      1
83            54  204606   833        0      0       0      1
84            49  125384   445        0      0       0      1
85            51  145179  1071        0      0       0      1
86            48  159770   670        0      0       0      1
87            67  153610   395        0      0       0      1
88            33  126581   671        0      0       0      1
89            49  155051  1056        0      0       0      1
90            60  116401   843        0      0       0      1
91            75  174370  1023        0      0       0      1
92            97  230801  1071        0      0       0      1
93            60  163253   295        0      0       0      1
94            56  146904  1195        0      0       0      1
95            39   90164   425        0      0       0      1
96            64  178775   547        0      0       0      1
97            33   60786   505        0      0       0      1
98            52   51503  1362        0      0       0      1
99            63  157571   948        0      0       0      1

[1200 rows x 7 columns]

In [61]:
# 한달에 한 가게가 받는 콜 수 column 추가
result['call_for_onestore'] = result['call']/result['total_number']

In [62]:
# Normalization으로 Min-Max scaler 사용
min_max_scaler = preprocessing.MinMaxScaler()
x = result['total_number'].values.astype(float)
x = x.reshape(-1,1)
x_scaled = min_max_scaler.fit_transform(x)
result['total_number'] = pd.DataFrame(x_scaled)

In [63]:
x = result['house'].values.astype(float)
x = x.reshape(-1,1)
x_scaled = min_max_scaler.fit_transform(x)
result['house'] = pd.DataFrame(x_scaled)

In [64]:
# Multivariable regression
LP_result = sm.ols(formula = 'call_for_onestore ~ total_number + house + morning + lunch + dinner + yasik', data = result).fit()

In [65]:
print(LP_result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:      call_for_onestore   R-squared:                       0.742
Model:                            OLS   Adj. R-squared:                  0.741
Method:                 Least Squares   F-statistic:                     688.1
Date:                Wed, 06 Dec 2017   Prob (F-statistic):               0.00
Time:                        23:50:31   Log-Likelihood:                -4522.1
No. Observations:                1200   AIC:                             9056.
Df Residuals:                    1194   BIC:                             9087.
Df Model:                           5
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       18.7359      0.581     32.237      0.000      17.596      19.876
total_number   -16.6199      1.820     -9.134      0.000     -20.190     -13.050
house            7.9367      1.689      4.698      0.000       4.622      11.251
morning        -12.8339      0.545    -23.546      0.000     -13.903     -11.764
lunch            1.9190      0.545      3.521      0.000       0.850       2.988
dinner          33.6991      0.545     61.826      0.000      32.630      34.769
yasik           -4.0484      0.545     -7.427      0.000      -5.118      -2.979
==============================================================================
Omnibus:                      184.621   Durbin-Watson:                   1.900
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              856.788
Skew:                           0.639   Prob(JB):                    8.93e-187
Kurtosis:                       6.938   Cond. No.                     6.07e+15
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.79e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.